require:
  - standard
  - rubocop-rails
  - rubocop-minitest

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/migrate/**/*
    - node_modules/**/*
    - config/environments/**/*
    - vendor/**/*

Rails:
  Enabled: true

Layout/HashAlignment:
  Exclude:
    - app/components/work_badge_component.rb

Layout/ExtraSpacing:
  Exclude:
    - app/components/work_badge_component.rb
